import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import '../constants/constants.dart';
import '../utils/arabic_text.dart';

/// Loads the bundled Quran text and its English translation.
///
/// The text is Tanzil's Uthmani edition and the translation is Saheeh
/// International, both generated by tool/build_content_assets.py. The earlier
/// bundled text had nine suras with verses merged or split; this source
/// matches the standard Hafs verse count for all 114.
abstract class QuranService {
  static final Map<String, List<String>> _arabic = {};
  static final Map<String, List<String>> _english = {};

  /// Parses raw sura text into one entry per verse.
  static List<String> parseVerses(String raw) => ArabicText.toLines(raw);

  /// Returns the Arabic verses of [suraId] (1-based).
  static Future<List<String>> loadSura(String suraId) async {
    final cached = _arabic[suraId];
    if (cached != null) return cached;

    final raw = await rootBundle.loadString('assets/quran/ar/$suraId.txt');
    final verses = parseVerses(raw);
    _arabic[suraId] = verses;

    assert(() {
      final mismatch = verseCountMismatch(suraId, verses.length);
      if (mismatch != null) debugPrint(mismatch);
      return true;
    }());

    return verses;
  }

  /// Returns the Saheeh International translation of [suraId], one entry per
  /// verse, aligned index-for-index with [loadSura].
  static Future<List<String>> loadTranslation(String suraId) async {
    final cached = _english[suraId];
    if (cached != null) return cached;

    final raw = await rootBundle.loadString('assets/quran/en/$suraId.txt');
    final verses = raw
        .split('\n')
        .map((l) => l.trim())
        .where((l) => l.isNotEmpty)
        .toList();
    _english[suraId] = verses;
    return verses;
  }

  /// Returns a description of the problem when the number of parsed verses
  /// disagrees with the sura's declared verse count, or null when they agree.
  static String? verseCountMismatch(String suraId, int parsedCount) {
    final id = int.tryParse(suraId);
    if (id == null || id < 1 || id > Constants.suraDataLists.length) {
      return 'Quran integrity: unknown sura id "$suraId"';
    }

    final sura = Constants.suraDataLists[id - 1];
    final expected = int.tryParse(sura.suraVersesNumber);
    if (expected == null || expected == parsedCount) return null;

    return 'Quran integrity: sura $suraId (${sura.suraNameEN}) parsed '
        '$parsedCount verses but declares $expected';
  }

  static void clearCache() {
    _arabic.clear();
    _english.clear();
  }
}
